apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: monolith:latest
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "dev-cluster-jwt-secret-minimum-32-chars"
    target:
      kind: Deployment
      name: monolith
  - patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
    target:
      kind: Service
      name: monolith-service
