apiVersion: batch/v1
kind: Job
metadata:
  name: model-train
  namespace: mlops
  labels:
    app: mlops-pipeline
    stage: train
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: mlops-pipeline
        stage: train
    spec:
      serviceAccountName: mlops-sa
      restartPolicy: Never
      containers:
        - name: train
          image: PLACEHOLDER_ECR_URL:latest
          args: ["--stage", "train"]
          envFrom:
            - configMapRef:
                name: mlops-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
