apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secrets.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  # ingress.yaml - overlay側で必要に応じて追加

labels:
  - pairs:
      app.kubernetes.io/part-of: eks-app-mlops-platform
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
