apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serviceaccount
  namespace: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: eks-app-mlops-platform
  annotations:
    # IRSA: eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/app-role
