/**
 * Integration test: auth service ↔ hono token compatibility
 *
 * Tests that tokens generated by apps/auth (Lambda auth service)
 * can be verified by hono when both use the same JWT_SECRET.
 */

import { describe, it, expect, beforeAll } from '@jest/globals'
import { sign, verify } from 'hono/jwt'

// Shared JWT secret (must be same for both apps)
const SHARED_JWT_SECRET = 'shared-secret-key-for-testing-32chars'

// Simulate auth service token generation (uses jose library with HS256)
async function createAuthToken(payload: { sub: string; email: string }) {
  const now = Math.floor(Date.now() / 1000)
  return sign(
    {
      ...payload,
      iat: now,
      exp: now + 3600,
    },
    SHARED_JWT_SECRET
  )
}

// Simulate hono token verification
async function verifyHonoToken(token: string) {
  try {
    const decoded = await verify(token, SHARED_JWT_SECRET)
    return {
      sub: decoded.sub as string,
      email: decoded.email as string,
      iat: decoded.iat as number,
      exp: decoded.exp as number,
    }
  } catch {
    return null
  }
}

describe('Auth Integration: auth service ↔ hono', () => {
  describe('Token Compatibility', () => {
    it('should verify auth service token in hono', async () => {
      // 1. Generate token like auth service would
      const payload = {
        sub: 'dummy-user-id',
        email: 'admin@example.com',
      }
      const token = await createAuthToken(payload)

      // 2. Verify token like hono would
      const verified = await verifyHonoToken(token)

      // 3. Assert
      expect(verified).not.toBeNull()
      expect(verified?.sub).toBe('dummy-user-id')
      expect(verified?.email).toBe('admin@example.com')
    })

    it('should have valid iat and exp claims', async () => {
      const token = await createAuthToken({
        sub: 'test-user',
        email: 'test@example.com',
      })

      const verified = await verifyHonoToken(token)

      expect(verified?.iat).toBeDefined()
      expect(verified?.exp).toBeDefined()
      expect(verified!.exp).toBeGreaterThan(verified!.iat)
    })

    it('should reject token with wrong secret', async () => {
      // Generate token with different secret
      const wrongSecretToken = await sign(
        {
          sub: 'test',
          email: 'test@example.com',
          iat: Math.floor(Date.now() / 1000),
          exp: Math.floor(Date.now() / 1000) + 3600,
        },
        'wrong-secret-key-that-is-32-chars!'
      )

      // Try to verify with correct secret - should fail
      const verified = await verifyHonoToken(wrongSecretToken)
      expect(verified).toBeNull()
    })
  })

  describe('Payload Format Compatibility', () => {
    it('should handle standard JWT claims', async () => {
      const now = Math.floor(Date.now() / 1000)
      const payload = {
        sub: 'user-123',
        email: 'user@example.com',
      }

      const token = await createAuthToken(payload)
      const decoded = await verifyHonoToken(token)

      expect(decoded?.sub).toBe('user-123')
      expect(decoded?.email).toBe('user@example.com')
      expect(typeof decoded?.iat).toBe('number')
      expect(typeof decoded?.exp).toBe('number')
    })
  })
})

console.log(`
===========================================
Token Compatibility Test Summary
===========================================
This test verifies that:
1. auth service and hono can use the same JWT_SECRET
2. Tokens generated by auth service can be verified by hono
3. The payload format (sub, email, iat, exp) is compatible

To run actual integration test:
1. Set JWT_SECRET env var to same value in both apps
2. Deploy auth service (make lambda-deploy)
3. Start hono: JWT_SECRET=xxx npm start
4. Login via /auth/login, use token in hono
===========================================
`)
