apiVersion: v1
kind: Service
metadata:
  name: llm-embeddings
  namespace: llm
spec:
  type: ClusterIP
  selector:
    app: llm-embeddings
  ports:
    - name: http
      port: 8001
      targetPort: 8001

