apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/component: exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
