apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{name}}
spec:
  amiSelectorTerms:
    - alias: {{amiAlias:al2@latest}}
  subnetSelectorTerms:
    - tags:
        kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{clusterName}}
  role: {{role:KarpenterNodeRole-}}{{clusterName}}
  blockDeviceMappings:
    - deviceName: {{deviceName:/dev/xvda}}
      ebs:
        volumeSize: {{volumeSize:200Gi}}
        volumeType: {{volumeType:gp3}}
        encrypted: {{encrypted:true}}
